all:
	@(cd libStdHeaderUnit;	make);
	@(cd libMyMath;			make);
	@(cd libMyGraph;		make);
	@(cd app1;				make);

clean:
	@(cd libStdHeaderUnit;	make clean);
	@(cd libMyMath;			make clean);
	@(cd libMyGraph;		make clean);
	@(cd app1;				make clean);
